fail to create on databases that aren't `UTF8` (#281)
PL/Rust can't support databases that aren't UTF8 because of Rust's requirements around Strings being proper UTF8.  This PR causes `CREATE EXTENSION plrust` to raise an ERROR in this case:

```sql
[v14.6][2495941] plrust=# create extension plrust;
ERROR:  PL/Rust only supports UTF8-encoded databases
```

This might be a little heavy-handed now but it gives us time to consider other options for relaxing this requirement.

The decision here stems from the fact that, currently, `pgx` blindly assumes all `TEXT` Datum conversions are valid UTF8, when they might not be.